class QuestionsMap
  @@QAHash = {"What is the name of the game?" => "Trivial Retreat",
            "Hg is the chemical symbol of which element?" => "Mercury",
            "Which email service is owned by Microsoft?" => "Hotmail",
            "Which country produces the most coffee in the world?" => "Brazil",
            "What was the first US state?" => "Delaware",
            "What is the capital city of Spain?" => "Madrid",
            "What is Chandler’s last name in the sitcom Friends?" => "Bing",
            "Which country invented tea?" => "China",
            "Pure water has a pH level of around? (1-14)" => "7",
            "Who starts first in chess?" => "White",
            "What language has the most words?" => "English",
            "Kodiak island is in which US state?" => "Alaska",
            "What is the world's largest ocean?" => "Pacific",

            "Which country do cities of Perth, Adelade & Brisbane belong to?" => "Australia",
            "What geometric shape is generally used for stop signs?" => "Octagon",
            "What is the name of the biggest technology company in South Korea?" => "Samsung",
            "Which animal can be seen on the Porsche logo?" => "Horse",
            "Worship of Krishna is observed by which Religious Faith?" => "Hinduism",
            "What is the common name for dried plums?" => "Prunes",
            "Which country consumes the most chocolate per capita?" => "Switzerland",
            "What was the first soft drink in space" => "Coca Cola",
            "What is the most consumed manufactured drink in the world?" => "Tea",
            "Which is the only edible food that never goes bad?" => "Honey",
            "Which country invented ice cream?" => "China",
            "From which country does Gouda cheese originate?" => "Netherlands",

            "What famous US festival hosted over 350,000 fans in 1969?" => "Woodstock",
            "Which country won the first-ever soccer World Cup in 1930?" => "Uruguay",
            "What sport is dubbed the \"king of sports\"?" => "Soccer",
            "Dump, floater, and wipe are terms used in which team sport?" => "Volleyball",
            "How many colors are there in the rainbow? (1-100)" => "7",
            "What color is a ruby?" => "Red",
            "What is Earth's largest continent?" => "Asia",
            "Area 51 is located in which U.S. state" => "Nevada",
            "What country touches the Indian Ocean, the Arabian Sea, and the Bay of Bengal?" => "India",
            "Which country borders 14 nations and crosses 8 time zones?" => "Russia",
            "Havana is the capital of what country?" => "Cuba",
            "What country has the most natural lakes?" => "Canada",

            "In what country would you find Lake Bled?" => "Slovenia",
            "How many hearts does an octopus have? (1-10)" => "3",
            "The unicorn is the national animal of which country?" => "Scotland",
            "How many legs does a spider have? (1-50)" => "8",
            "What type of animal is a Flemish giant?" => "Rabbit",
            "What is the hottest planet in the solar system?" => "Venus",
            "What is the opposite of matter" => "Antimatter",
            "What is the nearest planet to the sun?" => "Mercury",
            "What color is your blood when it’s inside your body?" => "Red",
            "What tissues connect the muscles to the bones?" => "Tendons",
            "Iceland diverted roads to avoid disturbing communities of what?" => "Elves",

            "What colour is the \"Ex\" in FedEx Ground?" => "Green",
            "What is Cynophobia the fear of?" => "Dogs",
            "What was the original name of the search engine \"Google\"?" => "BackRub",
            "What year was Queen Elizabeth II born?" => "1926",
            "What is the nationality of Picasso?" => "Spain",
            "In which book series does 'Neville Longbottom' appear?" => "Harry Potter",
            "What country find the \"Spanish Steps\"?" => "Italy",
            "Which country was split into two zones by the Yalta agreement?" => "Germany",
            "Who was the fourth president of the United States??" => "James Madison",
            "The “Hanging Gardens,” was found in which city?" => "Babylon",
            "Greenland was a colony of which country until 1981?" => "Denmark",
            "Which U.S. president had a home called The Hermitage?" => "Andrew Jackson",
            "In which country did the Easter Rising take place in 1916?" => "Ireland",
            "Which Greek historian is known as the “Father of History”?" => "Herodotus",
            "The Ptolemy dynasty ruled which ancient kingdom?" => "Egypt",

            "The ancient city of Rome was built on how many hills? (1-10)" => "7",
            "The Peloponnesian War was fought between Athens and ____?" => " Sparta",
            "What is the name of the first human civilization?" => "Mesopotamia",
            "What is the name of the tallest grass on earth?" => "Bamboo",
            "Which is the most abundant element in the universe?" => "Hydrogen",
            "What is the hardest natural substance on Earth?" => "Diamond",
            "On what continent will you not find bees?" => "Antarctica",
            "What is the only rock that floats?" => "Pumice",
            "What is the study of mushrooms called?" => "Mycology",
            "Does sound travel faster in the air or in water?" => "Water"


  }

  def self.QARet
    @@QAHash
  end
end
